<?php
//We need this so that the filter stays selected after submission
 
$jobCategories = [
    "Administration",
    "Agriculture",
    "Arts and Design",
    "Automotive",
    "Aviation",
    "Beauty",
    "Biotechnology",
    "Construction",
    "Consulting",
    "Customer Service",
    "Education",
    "Energy",
    "Engineering",
    "Entertainment",
    "Environmental",
    "Fashion",
    "Finance",
    "Fisheries",
    "Fitness",
    "Food Services",
    "Forestry",
    "Gaming",
    "Government",
    "Healthcare",
    "Hospitality",
    "Human Resources",
    "Information Technology",
    "Insurance",
    "Legal",
    "Logistics",
    "Manufacturing",
    "Maritime",
    "Marketing",
    "Media",
    "Mining",
    "Non-profit",
    "Pharmaceutical",
    "Real Estate",
    "Religious",
    "Research",
    "Retail",
    "Sales",
    "Science",
    "Social Services",
    "Space",
    "Sports",
    "Telecommunications",
    "Transportation",
    "Travel",
    "Utilities"  
];
?>